# Generated by Django 4.1.7 on 2023-05-04 04:44

from django.conf import settings
from django.db import migrations, models
import monitor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('name', models.CharField(default='New Monitor', max_length=50)),
                ('device_id', models.CharField(db_index=True, max_length=12, primary_key=True, serialize=False)),
                ('association_code', models.CharField(default=monitor.models.generate_association_code, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('averages', models.JSONField(default=monitor.models.default_averages, null=True)),
                ('user', models.ForeignKey(on_delete=models.SET(monitor.models.get_parked_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
